//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WPFArenda.DBModel
{
    using System;
    using System.Collections.Generic;
    
    public partial class Payments
    {
        public int ID_Payment { get; set; }
        public Nullable<int> ID_Contract { get; set; }
        public Nullable<System.DateTime> PaymentDate { get; set; }
        public Nullable<int> Amount { get; set; }
        public Nullable<int> ID_Method { get; set; }
    
        public virtual Contract Contract { get; set; }
        public virtual MethodPayment MethodPayment { get; set; }
    }
}
